### ISSUE TITLE
Can't get Swedish locale loaded for Scala application

### ISSUE THREAD

**Issue by jgrape** [heroku/heroku-buildpack-locale#4]
I set LANG=sv_SE.UTF-8 and have added the heroku-buildpack-locale to my app running on the Heroku-16 stack.

When the app fires up it makes a call to org.apache.commons.lang.LocaleUtils.toLocale("sv_SE.UTF-8") which throws an IllegalArgumentException since the locale is not available.

I have rebuilt the app several times and I can see in the build log that the Swedish language pack seems to be downloaded by the build pack.

**Comment by ojacobson** [comment]
Triage notes:

* Setting LANG=sv_SE.UTF-8 definitely does install the appropriate locale packages at build time:

        remote: The following additional packages will be installed:
        remote:   language-pack-sv
        remote: The following NEW packages will be installed:
        remote:   language-pack-sv language-pack-sv-base

    On inspection, those packages _are_ present in the slug.

* `locale -a` does not include those locales, even though `LOCPATH` and `I18NPATH` are set as per `.profile.d/000-locale.sh`.

I'll see what else I can dig up.

@jgrape Do you happen to know off the top of your head where `LocaleUtils.toLocale` looks for locale data? Does it respect `LOCPATH` or any other env vars?

**Comment by jgrape** [comment]
@ojacobson Looked in the source, and the Apache Commons Lang LocaleUtils tries to create a new locale using the standard java.util.Locale class. I don't know how the JVM looks for locale data though.

**Comment by dmathieu** [comment]
Note that the locale is properly installed, but also used by the system.

> ~ $ echo $LANG
sv_SE.UTF-8
~ $ date
fre 18 aug 2017 08:19:35 UTC

As we can't install system-wide packages, we're kind of hacking around it to use locally installed locales.
For that reason, you need to make sure that java loads those locales from the correct path.

I'm thinking this could happen because your program is started in a subshell, inside which the .profile.d scripts aren't loaded, and therefore the locales cannot be found?
See https://github.com/heroku/heroku-buildpack-locale/blob/master/bin/compile#L84-L85

**Comment by jgrape** [comment]
The application is using standard Heroku stuff for build an launch. It's build with the Scala build pack and launched as a web app in a dyno by Heroku. I'm  guessing the launch script is generated during build time and that the Heroku-16 stack launches it.

I have only written application code (Scala and Java). The rest is managed by Heroku.

Is it so that the two build packs (Scala and Locale) are not communicating properly?
Does Heroku runtime always ensure that the .profile.d scripts are executed before building and launching?

**Comment by dmathieu** [comment]
Jan,

At this point, it would be a lot easier if you opened a support ticket on help.heroku.com mentioning this GitHub issue.
It will be escalated to us, and we can take a more private look, as you'll be able to give us access to your running application so we can better investigate.

**Comment by jgrape** [comment]
I think I have found it.

The sv_SE.UTF-8 language pack is not present/downloaded. If I change the locale to sv_SE (without UTF-8) the application will launch without errors.

How can I ensure I have UTF-8 encoding for the Swedish language?

**Comment by dmathieu** [comment]
That's weird. Could you paste the full build output here? (from both LANG values).
When no encoding is set, we [default to utf-8](https://github.com/heroku/heroku-buildpack-locale/blob/master/bin/compile#L23). So you should be properly configured.

**Comment by jgrape** [comment]
I'm getting a really inconsistent behavior:

If I have a .locales file (regardless if it contains sv_SE.UTF-8 or just sv_SE), I **don't** get the correct locale loaded.

If I just rely on the LANG=sv_SE it works. The build pack warns about this way of configuring becoming deprecated and that I should use a .locales file though.

**Comment by jgrape** [comment]
If I only have *one* item in the `.locales` file it works as when setting the LANG variable (i.e the app is in the correct locale).
> sv_SE

**Comment by dmathieu** [comment]
I think I've found where the issue lies. Could you try using #5?
Remove the locale buildpack, then readd it on that PR's branch:

> heroku buildpacks:set https://github.com/heroku/heroku-buildpack-locale#en_break

**Comment by dmathieu** [comment]
#5 has been merged now. So just triggering a new build will give you that fix.

**Comment by dmathieu** [comment]
@jgrape are you still seeing the issue?
If so, could you paste the full output for your latest build producing the issue?
